name: For dev environment

on:
  push:
    branches:
      - main

jobs:
  build:
    env: 
      SHA: ${{ github.sha }}
  
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker build
        run : docker build -t terezabisharyan/myimage:latest .
      #- name: Docker run 
        #run : docker run -d --name dev-$SHA -p 3000:8080 myimage:latest
      - name: Docker push
        run : |
          docker login -u ${{secrets.HUB_UNAME}} -p ${{secrets.HUB_PSW}}
          docker push ${{secrets.HUB_UNAME}}/myimage:latest 
    services:
      my-image:
        image: terezabisharyan/myimage:latest
        ports: 
          - 3000:8080
      
